services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./backend:/app
      - attachments_data:/data/attachments
      - D:/:/mnt/f

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: []
