"""add auth roles and permissions

Revision ID: b69996e08f2f
Revises: e33bda35e355
Create Date: 2026-03-12 22:21:14.594066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql


# revision identifiers, used by Alembic.
revision: str = 'b69996e08f2f'
down_revision: Union[str, Sequence[str], None] = 'e33bda35e355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fix refresh_tokens FK to add ON DELETE CASCADE
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', schema='auth', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')

    # Create auth.roles
    op.create_table(
        'roles',
        sa.Column('id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('code', sa.String(50), unique=True, nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema='auth',
    )
    op.create_index('ix_auth_roles_code', 'roles', ['code'], schema='auth')

    # Create auth.permissions
    op.create_table(
        'permissions',
        sa.Column('id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('code', sa.String(100), unique=True, nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('module', sa.String(50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema='auth',
    )
    op.create_index('ix_auth_permissions_code', 'permissions', ['code'], schema='auth')
    op.create_index('ix_auth_permissions_module', 'permissions', ['module'], schema='auth')

    # Create auth.user_roles
    op.create_table(
        'user_roles',
        sa.Column('id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('role_id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
        schema='auth',
    )

    # Create auth.role_permissions
    op.create_table(
        'role_permissions',
        sa.Column('id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('role_id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('permission_id', sqlalchemy.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission'),
        schema='auth',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', schema='auth', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###
